version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - npm install -g sonarqube-scanner@latest

  build:
    commands:
      - npm install
      - npm run build

  post_build:
    commands:
      - sonar-scanner -Dsonar.projectKey=arjit547_react-repo123 -Dsonar.organization=arjit547 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}

      - |
        if [ $? -ne 0 ]; then
          echo "SonarCloud analysis failed. Sending email notification..."
          aws lambda invoke --function-name sonarlambda --payload "{\"exit_status\": $?}" output.txt
        else
          echo "SonarCloud analysis succeeded."
        fi

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
