version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      # Install SonarQube Scanner
      - npm install -g sonarqube-scanner

  build:
    commands:
      # Install Node.js dependencies
      - npm install
      # Build the React app
      - npm run build

  post_build:
    commands:
      # Run SonarCloud analysis
      - sonar-scanner -Dsonar.projectKey=arjit547_react-repo123 -Dsonar.organization=arjit547 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}
      # Capture the exit status of sonar-scanner
      - SONAR_EXIT_STATUS=$?

      # Check if sonar-scanner failed (non-zero exit status)
      - if [ $SONAR_EXIT_STATUS -ne 0 ]; then
          echo "SonarCloud analysis failed. Sending email notification..."
          # Invoke Lambda function with the exit status
          - aws lambda invoke --function-name sonarlambda --payload "{\"exit_status\": $SONAR_EXIT_STATUS}" output.txt
        else
          echo "SonarCloud analysis succeeded."
      fi

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
