version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - npm install -g sonarqube-scanner@latest

  build:
    commands:
      - npm install
      - npm run build

  post_build:
    commands:
      - sonar-scanner \
          -Dsonar.projectKey=arjit547_react-repo123 \
          -Dsonar.organization=arjit547 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${SONAR_TOKEN} \
          -Dsonar.qualitygate.wait=true  # Fail the build if quality gate is not met

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
