version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - npm install -g sonarqube-scanner@latest

  build:
    commands:
      - npm install
      - npm run build

  post_build:
  commands:
    - sonar-scanner -Dsonar.projectKey=arjit547_react-repo123 -Dsonar.organization=arjit547 -Dsonar.host.url=http://your-sonarqube-server -Dsonar.login=${SONAR_TOKEN}
    - SONAR_ISSUES=$(curl -s -u "${SONAR_TOKEN}": -X GET "http://your-sonarqube-server/api/measures/component?component=arjit547_react-repo123&metricKeys=bugs" | jq -r '.component.measures[0].value')
    - >
      if [ "$SONAR_ISSUES" -gt 0 ]; then
        echo "SonarQube analysis found $SONAR_ISSUES issues. Invoking Lambda function..."
        aws lambda invoke --function-name sonarlambda --payload "{\"exit_status\": 1}" output.txt
      else
        echo "SonarQube analysis succeeded. No issues found."
      fi


artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
