version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - npm install -g sonarqube-scanner@latest

  build:
    commands:
      - npm install
      - npm run build

  post_build:
    commands:
      - sonar-scanner -Dsonar.projectKey=arjit547_react-repo123 -Dsonar.organization=arjit547 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}
      - chmod +x sonar_analysis.sh
      - ./sonar_analysis.sh  # Execute the shell script

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
