version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      # Install SonarQube Scanner
      - npm install -g sonarqube-scanner

  build:
    commands:
      # Install Node.js dependencies
      - npm install
      # Build the React app
      - npm run build

  post_build:
    commands:
      # SonarCloud analysis
      - sonar-scanner -Dsonar.projectKey=arjit547_react-repo123 -Dsonar.organization=arjit547 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}
      # Continue with AWS CodeBuild steps (e.g., deploying artifacts)
      - aws lambda invoke --function-name sonarlambda --payload '{"detail": {"projectStatus": {"status": "ERROR", "qualityGate": {"conditions": "BUGS"}}}}' output.txt

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
